name: GFNxIDP
channels:
  - defaults
dependencies:
  - python=3.10
  - joblib
  - pandas
  - mdanalysis
  - numba
  - scikit-learn==1.6
  - matplotlib
  - numpy=1.26.4
  - pytorch
prefix: /opt/anaconda3/envs/GFNxIDP
