name: GFNxIDP
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0=h313beb8_0
  - biopython=1.85=py310h72d1ebd_0
  - blas=1.0=openblas
  - blosc=1.21.6=h7977b18_0
  - bottleneck=1.4.2=py310hbda83bc_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=py310hca03da5_0
  - cftime=1.6.4=py310h80987f9_0
  - contourpy=1.3.1=py310h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.17.0=py310hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py310h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.21.0=hbdbcc25_2
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py310h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - griddataformats=1.0.2=pyhd8ed1ab_1
  - gsd=4.0.0=py310h7bdd564_1
  - h5py=3.14.0=py310h2232773_0
  - harfbuzz=10.4.0=hb72c1af_0
  - hdf4=4.2.13=h5e329fb_3
  - hdf5=1.14.5=hd77251f_2
  - icu=75.1=hfee45f7_0
  - jinja2=3.1.6=py310hca03da5_0
  - joblib=1.5.2=py310hca03da5_0
  - jpeg=9f=h2f69dba_0
  - kiwisolver=1.4.8=py310h313beb8_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libaec=1.1.3=h313beb8_0
  - libavif=1.1.1=h80987f9_0
  - libcurl=8.15.0=hcdd2897_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.18=h23cfdf5_2
  - libllvm20=20.1.8=h1701f07_0
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnetcdf=4.9.3=h56724e0_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.30=hf2bb037_0
  - libopenjpeg=2.5.4=haa24f5a_0
  - libpng=1.6.50=h5c318fc_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.7.0=h91aec0a_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h4a9ca0c_1
  - libzip=1.8.0=h62fee54_1
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - llvmlite=0.45.1=py310hc8eb11b_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py310h80987f9_0
  - matplotlib=3.10.6=py310hca03da5_0
  - matplotlib-base=3.10.6=py310h066045a_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - mdanalysis=2.9.0=py310h5936506_1
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py310h062c92d_0
  - mpich=4.1.1=he2630cc_0
  - mpmath=1.3.0=py310hca03da5_0
  - mrcfile=1.5.4=pyhd8ed1ab_0
  - msgpack-python=1.1.1=py310h313beb8_0
  - ncurses=6.5=hee39554_0
  - netcdf4=1.7.2=py310hf82d5f1_2
  - networkx=3.4.2=py310hca03da5_0
  - numba=0.62.1=py310h471b49b_0
  - numexpr=2.11.0=py310h8c72970_1
  - numpy=1.26.4=py310h901140f_1
  - numpy-base=1.26.4=py310hae06d03_1
  - openjpeg=2.5.4=h959fc53_0
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=py310hca03da5_1
  - pandas=2.3.3=py310hc6ded6b_0
  - pcre2=10.46=h1dacb4a_0
  - pillow=11.3.0=py310h6dd570d_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - pyedr=0.8.0=pyhd8ed1ab_1
  - pyparsing=3.2.0=py310hca03da5_0
  - python=3.10.19=hcd7f573_2_cpython
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=1_cp310
  - pytng=0.3.3=py310h4f4b7e2_2
  - pytorch=2.2.2=py3.10_0
  - pytz=2025.2=py310hca03da5_0
  - pyyaml=6.0.2=py310h80987f9_0
  - readline=8.3=h0b18652_0
  - scikit-learn=1.6.0=py310h48c93d9_0
  - scipy=1.15.3=py310h132fc3c_1
  - seaborn=0.13.2=py310hca03da5_3
  - setuptools=72.1.0=py310hca03da5_0
  - six=1.17.0=py310hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - sympy=1.14.0=py310hca03da5_0
  - tbb=2022.0.0=h48ca7d4_0
  - threadpoolctl=3.5.0=py310h33ce5c2_0
  - tidynamics=1.1.2=pyhd8ed1ab_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py310h80987f9_0
  - tqdm=4.67.1=py310h33ce5c2_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - polyleven==0.9.0
prefix: /opt/anaconda3/envs/GFNxIDP
