name: GFNxIDP
channels:
  - bioconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas
  - matplotlib
  - numba
  - scikit-learn=1.2.2
  - mdanalysis
  - pytorch
  - blast

